"""change datetime to date in created

Revision ID: 182fb58e5122
Revises: 014a31ae3fcf
Create Date: 2025-06-09 00:35:39.538189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '182fb58e5122'
down_revision: Union[str, None] = '014a31ae3fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'created',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'created',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
